---
- name: chown wordpress
  file: path=/home/ubuntu/{{domain}} state=directory mode=0755 owner=www-data group=www-data
  become: yes
  become_method: sudo

- name: restart mysql
  service:
    name: mysql
    state: restarted

- name: restart apache2
  service:
    name: apache2
    state: restarted
