---
- name: Install mysql Server
  apt: name=mysql-server state=present update_cache=yes
  become: yes
  become_method: sudo

- name: Install other dependecies
  apt:
    name:
      - apache2
      - php5
      - mysql-server
      - libapache2-mod-php5
      - php5-mysql
    state: present
    update_cache: yes
  become: yes
  become_method: sudo

- name: install python mysql bindings
  apt: name=python-mysqldb state=installed
  become: yes
  become_method: sudo

- name: Database User creation
  mysql_user: name={{db_user}} password={{db_password}} priv=*.*:ALL state=present

- name: Database Creation
  mysql_db: name={{db_name}} state=present
  notify:
    - restart mysql



