---
- name: chown wordpress
  file: path=/home/{{user_name}}/{{domain}} state=directory mode=0755 owner={{user_name}} group={{user_name}}
  become: yes
  become_method: sudo


- name: install wp-cli
  get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: /usr/local/bin/wp
    force: yes
    mode: "a+x"

- name: copy wp cli config
  template:
    src: wp-cli.yml
    dest: "/home/{{user_name}}/wp-cli.local.yml"
    owner: "{{user_name}}"
    group: "{{user_name}}"
    mode: 0644

- name: copy theme
  copy:
    src: files/parallax-one.zip
    dest: "/home/{{user_name}}/parallax-one.zip"
    owner: "{{user_name}}"
    group: "{{user_name}}"
    mode: 0644

- name: copy theme
  copy:
    src: files/replete.zip
    dest: "/home/{{user_name}}/replete.zip"
    owner: "{{user_name}}"
    group: "{{user_name}}"
    mode: 0644

- name: remove wp-config.php
  file: path=/home/{{user_name}}/{{domain}}/wp-config.php state=absent

- name: download wordpress
  command: wp core download
  args:
    chdir: "/home/{{user_name}}"
  become_user: "{{user_name}}"
  register: download_result
  failed_when: "'already' not in download_result.stderr and 'Success' not in download_result.stdout"
  changed_when: "'Success' in download_result.stdout"

- name: config wordpress
  command: wp core config
  args:
    chdir: "/home/{{user_name}}"
  become_user: "{{user_name}}"
  register: config_result
  failed_when: "'already' not in config_result.stderr and 'Success' not in config_result.stdout"
  changed_when: "'Success' in config_result.stdout"

- name: install wordpress
  command: wp core install
  args:
    chdir: "/home/{{user_name}}"
  become_user: "{{user_name}}"
  register: install_result
  failed_when: "'already' not in install_result.stdout and 'Success' not in install_result.stdout"
  changed_when: "'Success' in install_result.stdout"


- name: install parallax one
  command: wp theme install /home/{{user_name}}/parallax-one.zip
  args:
    chdir: "/home/{{user_name}}"
  become_user: "{{user_name}}"
  register: install_parallax_result
  failed_when: "'already' not in install_result.stdout and 'Success' not in install_parallax_result.stdout"
  changed_when: "'Success' in install_parallax_result.stdout"

- name: install replete
  command: wp theme install /home/{{user_name}}/replete.zip
  args:
    chdir: "/home/{{user_name}}"
  become_user: "{{user_name}}"
  register: install_replete_result
  failed_when: "'already' not in install_result.stdout and 'Success' not in install_replete_result.stdout"
  changed_when: "'Success' in install_replete_result.stdout"

- name: chown wordpress
  file: path=/home/{{user_name}}/{{domain}} state=directory mode=0755 owner=www-data group=www-data
  become: yes
  become_method: sudo